name: Put dev code on server
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Push dev code to server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/dev_arthur_systems
            git pull
