name: Put stable code on server
on:
  push:
    branches:
      - stable
jobs:
  build:
    name: Push stable code to server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/arthur_systems
            git pull
            docker start vite_builder_stable -a
            docker run -d --rm --name clone_dummy -v arthur_systems:/root alpine tail -f /dev/null
            docker cp clone_dummy:/root ./dist/
            docker stop clone_dummy
